# Generated by Django 5.2 on 2025-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='route_end_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='route_start_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
