# Generated by Django 5.2 on 2025-04-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transport_route_end_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='quantity_kg',
            new_name='item_weight',
        ),
    ]
